---
all:
  hosts:
    macmini:
      ansible_host: 10.218.65.70
      ansible_user: macos
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_python_interpreter: /usr/bin/python3

    group-mac-mini:
      ansible_host: 10.218.65.70
      ansible_user: ladmin
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_python_interpreter: /usr/bin/python3

  vars:
    orchard_controller_host: macmini
    masters_as_nodes: true
    cluster_name: k8sfs-macmini
    kubectl_local_config: "{{ lookup('env', 'HOME') }}/.kube/k8sfs-macmini.config"
    gateway_address: 10.218.65.76
    lb_ip_pool_start: 10.218.65.76
    lb_ip_pool_stop: 10.218.65.79
    node_image_env: macmini
    node_gateway: 10.218.65.1
    node_image_registry: ghcr.io/jehoi-ga-ada/k8sfs-node
    node_image_registry_username: Jehoi-ga-ada
    node_image_registry_token: "{{ ghcr_token | default('') }}"

  children:
    bootstrap:
      hosts:
        group-mac-mini:

    orchard_controller:
      hosts:
        macmini:

    orchard_workers:
      hosts:
        macmini:

    k8s:
      children:
        master:
          hosts:
            master-1:
              ansible_host: 10.218.65.71
            master-2:
              ansible_host: 10.218.65.72
        worker:
          hosts:
            worker-1:
              ansible_host: 10.218.65.73
            worker-2:
              ansible_host: 10.218.65.74
        lb:
          hosts:
            lb-1:
              ansible_host: 10.218.65.75

    control_plane:
      children:
        master:
