---
all:
  hosts:
    jeho-mac:
      ansible_host: jeho.local
      ansible_user: jeho
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_python_interpreter: /usr/bin/python3

    macos:
      ansible_host: pg-mac
      ansible_user: macos
      ansible_python_interpreter: /usr/bin/python3

  vars:
    orchard_controller_host: macos
    use_tailscale: true
    masters_as_nodes: true

  children:
    bootstrap:
      hosts:
        jeho-mac:

    orchard_controller:
      hosts:
        macos:

    orchard_workers:
      hosts:
        macos:

    k8s:
      vars:
        ansible_ssh_common_args: '-o ProxyJump=macos@100.126.151.59'
      children:
        master:
        worker:
        lb:

    control_plane:
      children:
        master:
