---
kubeconfig_dir: /var/lib/kubernetes
admin_kubeconfig: "{{ kubeconfig_dir }}/admin.kubeconfig"

helm_url: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ kube_arch }}.tar.gz"
helm_release_dir: "/tmp/linux-{{ kube_arch }}"
helm_bin: /usr/local/bin/helm

cilium_repo: https://helm.cilium.io/
cilium_namespace: kube-system
cilium_release: cilium
cilium_chart: cilium
cilium_daemonset: cilium
cilium_operator_deployment: cilium-operator
cilium_rollout_timeout: 600s

loadbalancer_ip: "{{ hostvars['lb-1'].ansible_host }}"
apiserver_port: 6443

cilium_values_file: "{{ kubeconfig_dir }}/cilium-values.yaml"

cilium_addon_dir: "{{ kubeconfig_dir }}/addons"
cilium_lb_manifest: "{{ cilium_addon_dir }}/cilium-lb.yaml"

lb_lan_prefix: "{{ hostvars[master_node].ansible_host.split('.')[:3] | join('.') }}"
lb_ip_pool_name: lan-pool
l2_announce_policy_name: lan-announce

cilium_values:
  ipam:
    mode: kubernetes
  k8s:
    requireIPv4PodCIDR: true
  k8sServiceHost: "{{ loadbalancer_ip }}"
  k8sServicePort: "{{ apiserver_port }}"
  operator:
    replicas: 1
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  externalIPs:
    enabled: true
  k8sClientRateLimit:
    qps: 10
    burst: 20
