---
kube_binaries:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl

kubeconfig_dir: /var/lib/kubernetes
enc_dir: /var/lib/kubernetes/enc
cert_dir: /etc/ssl/certs
key_dir: /etc/ssl/private

kube_ca: "{{ cert_dir }}/ca.crt"
kube_ca_key: "{{ key_dir }}/ca.key"

loadbalancer_ip: "{{ hostvars['lb-1'].ansible_host }}"

apiserver_port: 6443
etcd_client_port: 2379

kubelet_preferred_address_types:
  - InternalIP
  - Hostname

control_plane_services:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
