---
- name: Ensure ~/.ssh exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"
  when: inventory_hostname == master_node

- name: Create ed25519 keypair (idempotent)
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    type: ed25519
  register: master1_key
  when: inventory_hostname == master_node

- name: Add "{{ master_node }}" pubkey to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ hostvars[master_node].master1_key.public_key }}"
  when: inventory_hostname != master_node

- name: Download kubectl
  ansible.builtin.get_url:
    url: "{{ kube_release_url }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: true
  when: inventory_hostname == master_node

- name: Check kubectl is working
  ansible.builtin.command: kubectl version --client
  register: kubectl
  changed_when: false
  when: inventory_hostname == master_node

- name: Kubectl version
  ansible.builtin.debug: msg="{{ kubectl.stdout }}"
  when: inventory_hostname == master_node
