---
- name: Download kubectl
  ansible.builtin.get_url:
    url: "{{ kube_release_url }}/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  become: true
  when: inventory_hostname == master_node

- name: Check kubectl is working
  ansible.builtin.command: kubectl version --client
  register: kubectl
  changed_when: false
  when: inventory_hostname == master_node

- name: Kubectl version
  ansible.builtin.debug: msg="{{ kubectl.stdout }}"
  when: inventory_hostname == master_node
