---
kubeconfig_dir: /var/lib/kubernetes
kube_proxy_dir: /var/lib/kube-proxy
cert_dir: /etc/ssl/certs
key_dir: /etc/ssl/private

loadbalancer_ip: "{{ hostvars['lb-1'].ansible_host }}"

control_plane_kubeconfigs:
  - admin.kubeconfig
  - kube-controller-manager.kubeconfig
  - kube-scheduler.kubeconfig

node_kubeconfigs:
  - kube-proxy.kubeconfig
