---
kubeconfig_dir: /var/lib/kubernetes
cert_dir: /etc/ssl/certs
key_dir: /etc/ssl/private

control_plane_kubeconfigs:
  - admin.kubeconfig
  - kube-controller-manager.kubeconfig
  - kube-scheduler.kubeconfig
