---
- name: Prerequisite for VM terraforming
  hosts: macos
  roles:
    - geerlingguy.mac.homebrew
  tasks:
    - name: Install qemu & libvirt
      community.general.homebrew:
        name: [qemu, libvirt]
        state: present

    - name: Start libvirt as a root service
      ansible.builtin.shell: sudo brew services start libvirt
      environment: { PATH: "/opt/homebrew/bin:{{ ansible_env.PATH }}" }

    - name: Add brew to PATH for shells
      ansible.builtin.lineinfile:
        path: ~/.zshenv
        line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
        create: true
