---
- name: Generate keypair on master-1
  hosts: master-1
  tasks:
    - name: Ensure ~/.ssh exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0700"

    - name: Create ed25519 keypair (idempotent)
      community.crypto.openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
        type: ed25519
      register: master1_key

- name: Authorize master-1's public key on all other nodes
  hosts: all:!master-1
  tasks:
    - name: Add master-1 pubkey to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ hostvars['master-1'].master1_key.public_key }}"

- name: Setup kubectl
  hosts: master-1
  tasks:
    - name: Download kubectl
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.36.0/bin/linux/arm64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: true

    - name: Check kubectl is working
      ansible.builtin.command: kubectl version --client
      register: kubectl
      changed_when: false

    - name: Kubectl version
      ansible.builtin.debug: msg="{{ kubectl.stdout }}"

- name: Setup TLS
  hosts: master-1
  become: true
  tasks:
    - name: Ensure csr dir exist
      ansible.builtin.file:
        path: /etc/ssl/csr
        state: directory
        mode: '0755'

    - name: Ensure certs dir exist
      ansible.builtin.file:
        path: /etc/ssl/certs
        state: directory
        mode: '0755'

    - name: Create private key for CA
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/ca.key
        size: 2048

    - name: Create CSR for CA
      community.crypto.openssl_csr:
        path: /etc/ssl/csr/ca.csr
        privatekey_path: /etc/ssl/private/ca.key
        common_name: KUBERNETES-CA

    - name: Sign CSR as a self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/ca.crt
        csr_path: /etc/ssl/csr/ca.csr
        privatekey_path: /etc/ssl/private/ca.key
        provider: selfsigned
        selfsigned_not_after: "+3650d"

    - name: Create private key for admin user
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/admin.key
        size: 2048

    - name: Create CSR for admin user
      community.crypto.openssl_csr:
        path: /etc/ssl/csr/admin.csr
        privatekey_path: /etc/ssl/private/admin.key
        common_name: ADMIN
        organization_name: system:masters

    - name: Sign CSR for admin using CA server private key
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/admin.crt
        csr_path: /etc/ssl/csr/admin.csr
        ownca_path: /etc/ssl/certs/ca.crt
        ownca_privatekey_path: /etc/ssl/private/ca.key
        provider: ownca

    - name: Create private key for controller manager
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/kube-controller-manager.key
        size: 2048

    - name: Create CSR for controller manager
      community.crypto.openssl_csr:
        path: /etc/ssl/csr/kube-controller-manager.csr
        privatekey_path: /etc/ssl/private/kube-controller-manager.key
        common_name: kube-controller-manager
        organization_name: system:kube-controller-manager

    - name: Sign CSR for controller manager using CA server private key
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/kube-controller-manager.crt
        csr_path: /etc/ssl/csr/kube-controller-manager.csr
        ownca_path: /etc/ssl/certs/ca.crt
        ownca_privatekey_path: /etc/ssl/private/ca.key
        provider: ownca

    - name: Create private key for kube proxy
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/kube-proxy.key
        size: 2048

    - name: Create CSR for kube proxy
      community.crypto.openssl_csr:
        path: /etc/ssl/csr/kube-proxy.csr
        privatekey_path: /etc/ssl/private/kube-proxy.key
        common_name: kube-proxy
        organization_name: system:node-proxier

    - name: Sign CSR for kube proxy using CA server private key
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/kube-proxy.crt
        csr_path: /etc/ssl/csr/kube-proxy.csr
        ownca_path: /etc/ssl/certs/ca.crt
        ownca_privatekey_path: /etc/ssl/private/ca.key
        provider: ownca

    - name: Create private key for kube scheduler
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/kube-scheduler.key
        size: 2048

    - name: Create CSR for kube scheduler
      community.crypto.openssl_csr:
        path: /etc/ssl/csr/kube-scheduler.csr
        privatekey_path: /etc/ssl/private/kube-scheduler.key
        common_name: kube-scheduler
        organization_name: system:kube-scheduler

    - name: Sign CSR for kube scheduler using CA server private key
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/kube-scheduler.crt
        csr_path: /etc/ssl/csr/kube-scheduler.csr
        ownca_path: /etc/ssl/certs/ca.crt
        ownca_privatekey_path: /etc/ssl/private/ca.key
        provider: ownca
