---
- name: Setup kubernetes cluster
  hosts: k8s
  roles:
    - cluster_ssh
    - cluster_tls
    - cluster_config
    - cluster_encryption
    - etcd
    - control_plane
    - container_runtime
    - worker
    - kubectl_access
