---
master_node: master-1
masters_as_nodes: false
metrics_server_version: "v0.9.0"
metrics_server_host_network: "{{ not (masters_as_nodes | bool) }}"
metrics_server_kubelet_insecure_tls: true
metrics_server_rollout_timeout: 300s
