---
worker_binaries:
  - kubelet

worker_services:
  - kubelet

kubeconfig_dir: /var/lib/kubernetes
kubelet_dir: /var/lib/kubelet
kubelet_pki_dir: /var/lib/kubelet/pki
cert_dir: /etc/ssl/certs
key_dir: /etc/ssl/private

kube_ca: "{{ cert_dir }}/ca.crt"
admin_kubeconfig: "{{ kubeconfig_dir }}/admin.kubeconfig"

loadbalancer_ip: "{{ hostvars['lb-1'].ansible_host }}"
apiserver_port: 6443

cluster_domain: cluster.local
cluster_dns: "{{ service_cidr.split('.')[:3] | join('.') }}.10"
containerd_socket: unix:///var/run/containerd/containerd.sock
resolv_conf: /run/systemd/resolve/resolv.conf

bootstrap_token: "{{ kubelet_bootstrap_token_id }}.{{ kubelet_bootstrap_token_secret }}"
bootstrap_token_secret_name: "bootstrap-token-{{ kubelet_bootstrap_token_id }}"
bootstrap_token_ttl_days: 7
bootstrap_token_expiration: "{{ '%Y-%m-%dT%H:%M:%SZ' | strftime(ansible_date_time.epoch | int + (bootstrap_token_ttl_days | int * 86400), utc=true) }}"
bootstrap_group: system:bootstrappers:worker
bootstrap_manifest_dir: /var/lib/kubernetes/bootstrap
kubelet_serving_signer: kubernetes.io/kubelet-serving
